// This file is automatically generated. Do not modify it manually.
import type { FirebaseOptions } from 'firebase/app';

// TODO: Replace with your actual Firebase project configuration.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "API_KEY",
  authDomain: "PROJECT_ID.firebaseapp.com",
  projectId: "PROJECT_ID",
  storageBucket: "PROJECT_ID.appspot.com",
  messagingSenderId: "SENDER_ID",
  appId: "APP_ID",
};
